version: "3.8"
services:
  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: change123
    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongodb/data:/data/db"
  postgres-db:
    image: postgres:latest
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: change123
        POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/data:/data/db"
